### ISSUE TITLE
warning about grad

### ISSUE THREAD

**Issue by SecretplayeRava** [fwu11/MCC#1]
thx for your excellent work first！
I got a warning when running this code on 3090cards：
UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [20, 768, 1, 1], strides() = [768, 1, 768, 768]
bucket_view.sizes() = [20, 768, 1, 1], strides() = [768, 1, 1, 1]
how to fix it？

**Comment by fwu11** [comment]
> thx for your excellent work first！ I got a warning when running this code on 3090cards： UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed. This is not an error, but may impair performance. grad.sizes() = [20, 768, 1, 1], strides() = [768, 1, 768, 768] bucket_view.sizes() = [20, 768, 1, 1], strides() = [768, 1, 1, 1] how to fix it？

Thank you for your kind words. Since these are just warnings, for me, I just ignore these.
